config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root 'home#index'
  resources :sample_cus_data
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/sample_cus_datum.rb
class SampleCusDatum < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!

  def index
  end
end

app/controllers/sample_cus_data_controller.rb
#require 'pycall/import'
#include PyCall::Import

class SampleCusDataController < ApplicationController
  before_action :set_sample_cus_datum, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  #before_action :correct_user

  # GET /sample_cus_data or /sample_cus_data.json
  def index
    @sample_cus_data = SampleCusDatum.all

    if params[:item_ids]
        @selected_items = @sample_cus_data.where(id: params[:item_ids]) if params[:item_ids]

        puts @selected_items.pluck(:first_name)

        redirect_to root_path
    else
        @selected_items = []
    end

  end

  # GET /sample_cus_data/1 or /sample_cus_data/1.json
  def show
  end

  # GET /sample_cus_data/new
  def new
    @sample_cus_datum = SampleCusDatum.new
  end

  # GET /sample_cus_data/1/edit
  def edit
  end

  # POST /sample_cus_data or /sample_cus_data.json
  def create
    @sample_cus_datum = SampleCusDatum.new(sample_cus_datum_params)

    respond_to do |format|
      if @sample_cus_datum.save
        format.html { redirect_to sample_cus_datum_url(@sample_cus_datum), notice: "Sample cus datum was successfully created." }
        format.json { render :show, status: :created, location: @sample_cus_datum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sample_cus_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sample_cus_data/1 or /sample_cus_data/1.json
  def update
    respond_to do |format|
      if @sample_cus_datum.update(sample_cus_datum_params)
        format.html { redirect_to sample_cus_datum_url(@sample_cus_datum), notice: "Sample cus datum was successfully updated." }
        format.json { render :show, status: :ok, location: @sample_cus_datum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sample_cus_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sample_cus_data/1 or /sample_cus_data/1.json
  def destroy
    @sample_cus_datum.destroy!

    respond_to do |format|
      format.html { redirect_to sample_cus_data_url, notice: "Sample cus datum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  #def correct_user
    #@sample_cus_datum = current_user.sample_cus_data.find_by(id:params[:id])
    #redirect_to home_index_path, notice: "Not Authorized to access data" if @sample_cus_datum.nil?
  #end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample_cus_datum
      @sample_cus_datum = SampleCusDatum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sample_cus_datum_params
      params.require(:sample_cus_datum).permit(:customerid, :first_name, :last_name, :destination, :phone, :date, :balance)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sample_cus_data_helper.rb
module SampleCusDataHelper
end

app/views/home/_footer.html.erb
<footer class="bg-body-tertiary text-center text-lg-start">

  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
    created by tonydarc
    <a class="text-body" href="">here</a>
  </div>
</footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary ">
  <div class="container-xxl bd-gutter flex-wrap flex-lg-nowrap">
    <%=link_to "Sample Site", home_index_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%=link_to "Home", home_index_path, class:"nav-link active"%>
        </li>
    <% if user_signed_in? %>
        <li class="nav-item">
          <%=link_to "View-All Listings", sample_cus_data_path, class:"nav-link active"%>
        </li>
        <li class="nav-item">
          <%=button_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link active"%>
        </li>
        <li class="nav-item">
          <%=link_to "Profile", edit_user_registration_path, class:"nav-link active"%>
        </li>
    <% else %>
        <li class="nav-item">
          <%=link_to "Login", new_user_session_path, class:"nav-link active"%>
        </li>
        <li class="nav-item">
          <%=link_to "Sign-up", new_user_registration_path, class:"nav-link active"%>
        </li>
    <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/home/_tableNave.hmtl.erb
<tr>
    <th scope = "col"></th>
    <th scope = "col">Customer Id</th>
    <th scope = "col">First Name</th>
    <th scope = "col">Last Name</th>
    <th scope = "col">Phone Number</th>
    <th scope = "col">Destination Name</th>
    <th scope = "col">Date</th>
    <th scope = "col">Balance Due</th>
    <th scope = "col"></th>
</tr>

app/views/home/_tableNave.html.erb
<tr>
    <th scope = "col"></th>
    <th scope = "col">Customer Id</th>
    <th scope = "col">First Name</th>
    <th scope = "col">Last Name</th>
    <th scope = "col">Phone Number</th>
    <th scope = "col">Destination Name</th>
    <th scope = "col">Date</th>
    <th scope = "col">Balance Due</th>
    <th scope = "col"></th>
</tr>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SefaProjSample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
    <%= render 'home/header' %>
    <div class="container">
    <%= yield %>
    <%= render 'home/footer' %>
    </div>
  </body>
</html>

app/views/sample_cus_data/_form.html.erb
<%= form_with(model: sample_cus_datum) do |form| %>
  <% if sample_cus_datum.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sample_cus_datum.errors.count, "error") %> prohibited this sample_cus_datum from being saved:</h2>

      <ul>
        <% sample_cus_datum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :customerid, style: "display: block" %>
    <%= form.text_field :customerid %>
  </div>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :destination, style: "display: block" %>
    <%= form.text_field :destination %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :balance, style: "display: block" %>
    <%= form.text_field :balance %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sample_cus_data/_sample_cus_datum.html.erb
<div id="<%= dom_id sample_cus_datum %>">

    <tr>
        <td><input class="form-check-input selectable" type="checkbox" name="item_ids[]" value="<%= sample_cus_datum.id %>"></td>
        <td><%= sample_cus_datum.customerid %></td>
        <td><%= sample_cus_datum.first_name %></td>
        <td><%= sample_cus_datum.last_name %></td>
        <td><%= sample_cus_datum.phone %></td>
        <td><%= sample_cus_datum.destination %></td>
        <td><%= sample_cus_datum.date %></td>
        <td><%= sample_cus_datum.balance %></td>
        <td> <%= link_to "Show", edit_sample_cus_datum_path(sample_cus_datum) %></td>
    </tr>
</div>

app/views/sample_cus_data/edit.html.erb
<h1>Editing sample cus datum</h1>

<%= render "form", sample_cus_datum: @sample_cus_datum %>

<br>

<div>
  <%= link_to "Show this sample cus datum", @sample_cus_datum %> |
  <%= link_to "Back to sample cus data", sample_cus_data_path %>
</div>

app/views/sample_cus_data/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Listings</h1>

<div id="sample_cus_data">
    <%= form_with url: sample_cus_data_path, method: :get, local: true do %>
    <table class= "table table-striped table-bordered table-hover">
        <th data-sort-ignore="true"><input type="checkbox" id="selectAll"></input></th>
        <thead>
            <%= render 'home/tableNave'  %>
        </thead>
        <tbody>
        <% @sample_cus_data.each do |sample_cus_datum| %>
            <%= render sample_cus_datum %>
            <p>
            </p>
        <% end %>
        </tbody>

    <tfoot>
        <%= render 'home/tableNave'  %>
    </tfoot>
    </table>
    <%= submit_tag "Submit Selected" %>
    <% end %>
</div>

<%= link_to "New sample cus datum", new_sample_cus_datum_path %>

app/views/sample_cus_data/new.html.erb
<h1>New sample cus datum</h1>

<%= render "form", sample_cus_datum: @sample_cus_datum %>

<br>

<div>
  <%= link_to "Back to sample cus data", sample_cus_data_path %>
</div>

app/views/sample_cus_data/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sample_cus_datum %>

<div>
  <%= link_to "Edit this sample cus datum", edit_sample_cus_datum_path(@sample_cus_datum) %> |
  <%= link_to "Back to sample cus data", sample_cus_data_path %>

  <%= button_to "Destroy this sample cus datum", @sample_cus_datum, method: :delete %>
</div>